### ISSUE TITLE
Container monitor

### ISSUE THREAD

**Issue by at15** [xephonhq/xephon-b#16]
We need to provide some insight about the databases, like if a database fails with most of the system idle, there is certainly wrong configuration or poor design.

Existing solutions 

- https://github.com/stefanprodan/dockprom Docker hosts and containers monitoring with Prometheus, Grafana, cAdvisor, NodeExporter and AlertManager, provide configuration files to glue them together, Prometheus is used as TSDB, Grafana is used for visualization, cAdvisor for container monitor, NodeExporter for host metrics
- https://github.com/vegasbrianc/docker-monitoring similar to dockerprom
- https://github.com/weaveworks/scope Monitoring, visualisation & management for Docker & Kubernetes
- http://rancher.com/comparing-monitoring-options-for-docker-deployments/
- https://grafana.net/dashboards/1244 a dashboard for monitoring prometheus using grafana

Ref 

- https://github.com/iovisor/bcc  Tools for BPF-based Linux IO analysis, networking, monitoring, and more
- https://github.com/facebook/osquery query system metrics using SQL

**Comment by at15** [comment]
@gaocegege got any idea for this? thx

**Comment by gaocegege** [comment]
I'm not familiar with these tools, sorry about it :)))

**Comment by at15** [comment]
Inspired by https://github.com/linkedin/dr-elephant, I think I can name the sub package `dr.chen` @czheo /w\
